### ISSUE TITLE
Default in-memory storage implementation

### ISSUE THREAD

**Issue by chunningham** [jolocom/jolocom-sdk#17]
### Scope of the feature

A naive implementation of the IStorage interface using simple objects as maps. This is useful for development and testing.

### Tasks

*Enumerate the tasks that are needed to implement the feature*

- [ ] implement IStorage interface
  - [ ] implement IStorageGet interface
  - [ ] implement IStorageStore interface
  - [ ] implement IStorageDelete interface
- [ ] test with previous storage tests

### Additional important information

It should be made clear to library consumers that this is not intended for production use.
