### ISSUE TITLE
organise polyfills

### ISSUE THREAD

**Issue by chunningham** [jolocom/jolocom-sdk#5]
### Description
`src/node.polyfills.ts` contains implementations of functions from React Native, for NodeJS. `tsconfig.json` contains a `paths` section which redirects the import statements for the relevant modules to `src/node.polyfills.ts`. In compilation however, these paths are not correctly preserved in JS, so running results in a `missing module` error.

### TODO
- [x] implement a `runtime` module which imports the correct components
- [x] import from the `runtime` module
- [x] import from `node.polyfill.ts` inside the `runtime` module

**Comment by chunningham** [comment]
closed by #7
