### ISSUE TITLE
interaction continuation

### ISSUE THREAD

**Issue by chunningham** [jolocom/jolocom-sdk#77]
### Scope of the feature

Allow interactions to be continued with different Agent instances that share a DID (decouple Interaction from Agent instance).

### Tasks

*Enumerate the tasks that are needed to implement the feature*

- [x] ensure correct storage of all interaction tokens
- [x] read from storage when continuing an interaction
- [ ] remove internal token list from Agents (make them as stateless as possible)

**Comment by chunningham** [comment]
closed by #80
